// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcwutmqifgiungdoekwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjd3V0bXFpZmdpdW5nZG9la3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDg0OTgsImV4cCI6MjA3ODAyNDQ5OH0.kpLepL76vPBLdwnL3OXZzMs9qjip-MCHdpvY8y2E-1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});